In [1]:
import numpy as np

In [2]:
myarr=np.array([2,10,24,12], np.int64)

In [3]:
myarr

array([ 2, 10, 24, 12])

In [4]:
myarr[0]

np.int64(2)

In [5]:
myarr.shape

(4,)

In [6]:
myarr.dtype

dtype('int64')

In [7]:
myarr[0]=4

In [8]:
myarr

array([ 4, 10, 24, 12])

# Array creation: Conversion from other Python structures

In [9]:
listarray=np.array([[1,2,3],[4,5,6],[8,8,9]])

In [10]:
listarray

array([[1, 2, 3],
       [4, 5, 6],
       [8, 8, 9]])

In [11]:
listarray.shape

(3, 3)

In [12]:
listarray.dtype

dtype('int64')

In [13]:
listarray.size

9

In [14]:
zeros=np.zeros((2,5))

In [15]:
zeros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [16]:
zeros.dtype

dtype('float64')

In [17]:
rng=np.arange(10)

In [18]:
rng

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [19]:
lspace=np.linspace(1,5,4)

In [20]:
lspace

array([1.        , 2.33333333, 3.66666667, 5.        ])

In [21]:
emp=np.empty((4,4))

In [22]:
emp

array([[4.67296746e-307, 1.69121096e-306, 1.29060871e-306,
        1.24612081e-306],
       [1.24611945e-306, 8.34441742e-308, 1.78022342e-306,
        6.23058028e-307],
       [9.79107872e-307, 6.89807188e-307, 7.56594375e-307,
        6.23060065e-307],
       [1.78021527e-306, 8.34454050e-308, 1.11261027e-306,
        2.04712907e-306]])

In [23]:
emp_like=np.empty_like(lspace)

In [24]:
emp_like

array([1.        , 2.33333333, 3.66666667, 5.        ])

In [25]:
ide=np.identity(10)

In [26]:
ide

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [27]:
ide.shape

(10, 10)

In [28]:
arr=np.arange(99)

In [29]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [30]:
arr.reshape(3,33)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
        49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64,
        65],
       [66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98]])

In [31]:
arr1=np.arange(100)

In [32]:
arr1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [33]:
arr1=arr1.reshape(4,25)

In [34]:
arr1

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40,
        41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65,
        66, 67, 68, 69, 70, 71, 72, 73, 74],
       [75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90,
        91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [35]:
arr1=arr1.ravel()

In [36]:
arr1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [37]:
arr.shape

(99,)

# Numpy Axis

In [38]:
x=[[1,2,3],[4,5,6],[7,1,0]]

In [39]:
ar=np.array(x)

In [41]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [42]:
ar.sum(axis=0)

array([12,  8,  9])

In [43]:
ar.sum(axis=1)

array([ 6, 15,  8])

In [44]:
ar.T

array([[1, 4, 7],
       [2, 5, 1],
       [3, 6, 0]])

In [45]:
for item in ar.flat:
    print(item)

1
2
3
4
5
6
7
1
0


In [46]:
ar.ndim

2

In [47]:
ar.size

9

In [48]:
ar.nbytes

72

In [51]:
 one=np.array([1,3,4,63,2])

In [52]:
one.argmax()

np.int64(3)

In [53]:
one.argmin()

np.int64(0)

In [54]:
one.argsort()

array([0, 4, 1, 2, 3])

In [55]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [56]:
ar.argmin()

np.int64(8)

In [57]:
ar.argmax()

np.int64(6)

In [58]:
ar.argmax(axis=0)

array([2, 1, 1])

In [59]:
ar.argmax(axis=1)

array([2, 2, 0])

In [60]:
ar.argsort(axis=0)

array([[0, 2, 2],
       [1, 0, 0],
       [2, 1, 1]])

In [61]:
ar.argsort(axis=1)

array([[0, 1, 2],
       [0, 1, 2],
       [2, 1, 0]])

In [62]:
ar.ravel()

array([1, 2, 3, 4, 5, 6, 7, 1, 0])

In [63]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [64]:
ar2=np.array([[1, 2, 1],
       [4, 0, 6],
       [8, 1, 0]])

In [65]:
ar+ar2

array([[ 2,  4,  4],
       [ 8,  5, 12],
       [15,  2,  0]])

In [66]:
ar*ar2

array([[ 1,  4,  3],
       [16,  0, 36],
       [56,  1,  0]])

In [67]:
np.sqrt(ar)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 1.        , 0.        ]])

In [68]:
ar.sum()

np.int64(29)

In [69]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 1, 0]])

In [70]:
np.where(ar>5)

(array([1, 2]), array([2, 0]))

In [71]:
type(np.where(ar>5))

tuple

In [73]:
np.count_nonzero(ar)

8

In [74]:
import sys

In [75]:
py_ar=[0,4,5,2]

In [76]:
np_ar=np.array(py_ar)

In [77]:
sys.getsizeof(1) * len(py_ar)

112

In [82]:
np_ar.itemsize * np_ar.size

32

In [83]:
np_ar.tolist()

[0, 4, 5, 2]