In [1]:
import numpy as np

In [2]:
myarr=np.array([2,10,24,12])

In [3]:
myarr

array([ 2, 10, 24, 12])

In [4]:
print(type(myarr))

<class 'numpy.ndarray'>


In [5]:
myarr.dtype

dtype('int64')

In [6]:
myarr=np.array([2,10,24,12],np.int64)

In [7]:
myarr.dtype

dtype('int64')

In [8]:
myarr=np.array([2,10,24,12.3])

In [9]:
myarr.dtype

dtype('float64')

In [10]:
for i in myarr:
    print(i)

2.0
10.0
24.0
12.3


In [11]:
print(myarr[0:3])

[ 2. 10. 24.]


In [12]:
zeros=np.zeros((2,5))

In [13]:
zeros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [14]:
zeros=np.ones((2,5))

In [15]:
zeros

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [16]:
ide=np.eye(4)

In [17]:
ide

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [18]:
ide=np.identity(4)

In [19]:
ide

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [20]:
rand=np.random.random((2,5))

In [21]:
rand

array([[0.54793595, 0.54327516, 0.01521103, 0.81667502, 0.44630661],
       [0.67241788, 0.64985035, 0.39578539, 0.69731149, 0.60918143]])

In [22]:
myarr=np.array([2,10,24,12])

In [23]:
print(sum(myarr))

48


In [24]:
print(min(myarr))

2


In [25]:
print(max(myarr))

24


In [26]:
print(myarr.mean())

12.0


In [27]:
my_list=[1,2,3,4,5]
arr=np.array(my_list)
print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [28]:
print("first element",arr[0])
print("last element",arr[-1])


first element 1
last element 5


In [29]:
print(arr*2)

[ 2  4  6  8 10]


In [30]:
print(my_list*2)

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5]


In [31]:
arr

array([1, 2, 3, 4, 5])

In [32]:
print(arr+50)

[51 52 53 54 55]


In [33]:
arr=np.arange(12,39)

In [34]:
arr

array([12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28,
       29, 30, 31, 32, 33, 34, 35, 36, 37, 38])

In [35]:
arr.reshape(3,9)

array([[12, 13, 14, 15, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38]])

In [36]:
arr5=np.ones(10)
print(arr5*5)

[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]


In [37]:
arr6=[1,2,3],[4,5,6]
arr7=np.array(arr6)
print(arr7)
print(type(arr6))
print(type(arr7))

[[1 2 3]
 [4 5 6]]
<class 'tuple'>
<class 'numpy.ndarray'>


In [38]:
temperatures = np.array([23, 25, 20, 22, 26, 24, 21])
print(np.where(temperatures>22)) # provide index value

(array([0, 1, 4, 5]),)


In [39]:
temperatures = np.array([23, 25, 20, 22, 26, 24, 21])
print(np.where(temperatures<22)) # provide index value

(array([2, 6]),)


In [40]:
transpose=np.array([[0, 1, 2],
       [0, 1, 2],
       [2, 1, 0]])

In [41]:
transpose

array([[0, 1, 2],
       [0, 1, 2],
       [2, 1, 0]])

In [42]:
transpose.T  #T-- Transpose , convert row to columns and vice versa

array([[0, 0, 2],
       [1, 1, 1],
       [2, 2, 0]])

In [45]:
sales = np.array([23, 25, 20, 22, 26, 24, 21,30])
print(np.split(sales,4))

[array([23, 25]), array([20, 22]), array([26, 24]), array([21, 30])]


In [49]:
print(np.sort(sales))

[20 21 22 23 24 25 26 30]


In [50]:
print(np.argsort(sales))  # sort based on index value

[2 6 3 0 5 1 4 7]
